version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock